### PR TITLE
My operator work

### PR DESCRIPTION
**Pull request by urbach**
@amabdelrehim this pull adds a CG solver for the non even/odd operator. The solver does converge, but the check of the result fails...

### CODE REVIEW

**Comment by amabdelrehim** [comment]
Hi Carsten,

```
Excuse me but I didn't understand what you meant in this e-mail. Did
```

you mean for me to fix something or to accept a pull request from you?

Cheers,
Abdou

**Comment by urbach** [comment]
You can accept my pull request, and then you may check, whether the solver converges for you, or not (like for me). Maybe I did something wrong with your operator, but the easiest way to check it is to invert. As I wrote, CG converges, but the result is not correct.

**Comment by amabdelrehim** [comment]
Hi Carsten,

```
OK. Thanks, I will check.
```

Abdou

**Comment by urbach** [comment]
Hi! Okay, found the problem. Now it converges and the check at the end is successful. Please check!

**Comment by amabdelrehim** [comment]
OK. Good!

**Comment by urbach** [comment]
@amabdelrehim Abdou, I think the SSE2/SSE3 versions do not work. Did you check this?

**Comment by amabdelrehim** [comment]
Hi Carsten,

```
I didn't check yet. You mean it doen't compile or it produces wrong
```

results?

Cheers,
Abdou

**Comment by urbach** [comment]
well, try the inverter. It compiles, but...

**Comment by urbach** [comment]
for the inverter you have to use my branch, of course, or merge it into yours.

**Comment by amabdelrehim** [comment]
OK. I will test it.

Cheers

**Comment by urbach** [comment]
and, does it work for you?

**Comment by amabdelrehim** [comment]
I need to do the test :)

**Comment by urbach** [comment]
hmm, any news on this front...?

**Comment by amabdelrehim** [comment]
Hi Carsten,

```
 I am so sorry I didn't follow on this. I took time off and couldn't
```

keep up with things. I'll be very glad to continue. Could you please tell
me again where to start?

Cheers,
Abdou

**Pull request closed without merging**
